/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_Indication_SWC_.c
 * Generated on: Sat Jul 27 1:51:33 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorLock_Indication_SWC.h"


extern const Rte_CDS_DoorLock_Indication_SWC Rte_Instance_DoorLock_Indication_SWC;
extern const Rte_CDS_DoorLock_Indication_SWC * const Rte_Inst_DoorLock_Indication_SWC;


extern Std_ReturnType DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Buffer_retcode;

extern FunctionPtr_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Delegate;

DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_Indication_SWC_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State(myuint8 DoorLock_State)
{
	(Rte_Inst_DoorLock_Indication_SWC)->DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State->value = DoorLock_State;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorLock_Indication_SWC_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State(void)
{
	return &(Rte_Inst_DoorLock_Indication_SWC)->DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorLock_Indication_SWC_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State(void)
{
	return (Rte_Inst_DoorLock_Indication_SWC)->DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State->value;
}
DECLSPEC_EXPORT void ARUnit_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_ReturnCode(Std_ReturnType returnCode)
{
	DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Buffer_retcode = returnCode;
}

DECLSPEC_EXPORT void ARUnit_Set_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Delegate(FunctionPtr_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch  delegate)
{
	Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Delegate = delegate;
}

DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_Indication_SWC_DoorLock_Indication_Runnable(void)
{
	DoorLock_Indication_Runnable();
}
