/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorSensorAbstractionSWC_.c
 * Generated on: Sat Jul 27 1:51:33 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorSensorAbstractionSWC.h"


extern const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC;
extern const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC;




DECLSPEC_EXPORT void ARUnit_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State(myuint8 DoorLock_State)
{
		(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorSens_DoorLock_State->value = DoorLock_State;
}
DECLSPEC_EXPORT myuint8* ARUnit_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorSens_DoorLock_State->value;
}
DECLSPEC_EXPORT myuint8 ARUnit_IRead_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State(void)
{
	return (Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorSens_DoorLock_State->value;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_DoorSensorAbstractionSWC_LedSwitch_Runnable(myuint8 LED_State)
{
	return LedSwitch_Runnable(LED_State);
}


DECLSPEC_EXPORT void ARUnit_Trigger_DoorSensorAbstractionSWC_ReadDoorSensor_Runnable(void)
{
	ReadDoorSensor_Runnable();
}
