/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_Indication_SWC.h
 * Generated on: Sat Jul 27 1:51:33 EET
 ********************************************************************/

#ifndef RTE_DOORLOCK_INDICATION_SWC_H
#define RTE_DOORLOCK_INDICATION_SWC_H

#include "../RTE_Generated/Rte_DoorLock_Indication_SWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
//typedef const Rte_CDS_DoorLock_Indication_SWC *  const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorLock_Indication_SWC * const Rte_Inst_DoorLock_Indication_SWC;

/************************ application errors *************************/

#define RTE_E_IF_CS_LED_E_Ok ((Std_ReturnType)0)
#define RTE_E_IF_CS_LED_E_Not_Ok ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_SR_DoorState
 * Interface:	IF_SR_DoorLockSens
 * DataElement:	DoorLock_State
 * Runnable:	DoorLock_Indication_Runnable
 *****************************************************/
extern myuint8 Rte_IRead_DoorLock_Indication_SWC_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State (void);
#ifndef IN_RTE_C
#define Rte_IRead_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State() \
	Rte_IRead_DoorLock_Indication_SWC_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State()
#endif

/*****************************************************
 * Port: 		RP_CS_LedSwitch
 * Interface:	IF_CS_LED
 * Operation:	LED_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch (myuint8 LED_State);
#ifndef IN_RTE_C
#define Rte_Call_RP_CS_LedSwitch_LED_Switch(LED_State) \
	Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch(LED_State)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	DoorLock_Indication_Runnable
 * Period:		0.012
 *****************************************************/
extern void DoorLock_Indication_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch)(myuint8 LED_State);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCK_INDICATION_SWC_H */
