/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_Indication_SWC_.c
 * Generated on: Sat Jul 27 1:51:33 EET
 ********************************************************************/

#include "../RTE_Generated/Rte_DoorLock_Indication_SWC.h"

#include "string.h"

Rte_DE_myuint8 ReadDoorSensor_PP_SR_DoorSens_DoorLock_State;


Rte_DE_myuint8 DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State;


const Rte_CDS_DoorLock_Indication_SWC Rte_Instance_DoorLock_Indication_SWC = {
&ReadDoorSensor_PP_SR_DoorSens_DoorLock_State
};

const Rte_CDS_DoorLock_Indication_SWC * const Rte_Inst_DoorLock_Indication_SWC = &Rte_Instance_DoorLock_Indication_SWC;


Std_ReturnType DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Delegate = 0;

myuint8 Rte_IRead_DoorLock_Indication_SWC_DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State (void)
{
	return (Rte_Inst_DoorLock_Indication_SWC)->DoorLock_Indication_Runnable_RP_SR_DoorState_DoorLock_State->value;
}
Std_ReturnType Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch (myuint8 LED_State)
{
	Std_ReturnType __result = DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_Indication_SWC_RP_CS_LedSwitch_LED_Switch_Delegate(LED_State);
	}

	/* Synch. call for the needed Runnable to be activated */
	LedSwitch_Runnable(LED_State);

	return __result;
}
