/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC.h
 * Generated on: Sat Jul 27 1:51:33 EET
 ********************************************************************/

#ifndef RTE_DOORSENSORABSTRACTIONSWC_H
#define RTE_DOORSENSORABSTRACTIONSWC_H

#include "Rte_DoorSensorAbstractionSWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC;

/************************ application errors *************************/

#define RTE_E_IF_CS_LED_E_Ok ((Std_ReturnType)0)
#define RTE_E_IF_CS_LED_E_Not_Ok ((Std_ReturnType)1)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		PP_SR_DoorSens
 * Interface:	IF_SR_DoorLockSens
 * DataElement:	DoorLock_State
 * Runnable:	ReadDoorSensor
 *****************************************************/
extern void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State (myuint8 DoorLock_State);
#ifndef IN_RTE_C
#define Rte_IWrite_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State(RTEData) \
	Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State(RTEData)
#endif
extern myuint8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State() \
	Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorSens_DoorLock_State()
#endif

/*****************************************************
 * Port: 		PP_CS_LedSwitch
 * Interface:	IF_CS_LED
 * Operation:	LED_Switch
 *****************************************************/
extern Std_ReturnType LedSwitch_Runnable(myuint8 LED_State) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ReadDoorSensor
 * Period:		0.01
 *****************************************************/
extern void ReadDoorSensor_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORSENSORABSTRACTIONSWC_H */
